name: Generate Article from Upload

on:
  push:
    paths:
      - 'static/images/uploaded/**'

jobs:
  generate-article:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai pillow python-dotenv

      - name: Run article generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python api/generate_article.py

      - name: Commit and push new article
        run: |
          git config --global user.name 'AutoNewsBot'
          git config --global user.email 'autobot@example.com'
          git add articles/ templates/data/article_index.json
          git commit -m "📝 New article generated" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/artex137/News-Input-test.git HEAD:main
